### ISSUE TITLE
Did not wire up correct version of react peer dependency for react-typeahead

### ISSUE THREAD

**Issue by togakangaroo** [Workiva/karma-jspm#108]
I'm not sure if this is a jspm error or a dependency spec error for react-typeahead

I have a project in which I have `react 0.13.2`. I did an install of `react-typeahead 1.1.45 Which [lists](https://github.com/fmoo/react-typeahead/blob/master/package.json) `react 0.14.0` as a peer dependency. This installed fine and did not force my version of react to update. The problem is that this version of react-typeahead actually doesn't work. The method to filter out options seems to depend on new behavior introduced in react 0.14.

Seems like maybe the peer dependency should have either been forced by jspm or the install failed.

**Comment by maxwellpeterson-wf** [comment]
This project is solely concerned with testing jspm projects using Karma. Perhaps open an issue on https://github.com/jspm/jspm-cli.
