### ISSUE TITLE
Support loading new files

### ISSUE THREAD

**Issue by sylvain-hamel** [Workiva/karma-jspm#121]
When a file is added, karma detects it and reloads the tests, the plug-in's `loaded` function is invoked but the file list is not refreshed so its doesn't load (`System.import`) the new file.

**Comment by FrederikNS** [comment]
This is very annoying, every time I add a new test file, I have to stop karma, and then start it up again. Otherwise it doesn't run any of the tests in the new file.

**Comment by FrederikNS** [comment]
@sylvain-hamel: I figured out what needed to be changed for the new files to be loaded automatically, and have submitted a pull request. If you are impatient, you can simply apply my change to your karma-jspm.

**Comment by sylvain-hamel** [comment]
@FrederikNS Thanks!
