### ISSUE TITLE
Unable to get working with JSPM 0.17 beta

### ISSUE THREAD

**Issue by rafi-cengage** [Workiva/karma-jspm#127]
Has anyone had any luck getting this to work with the new JSPM beta? It now has a browser confit file as well as a JSPM config. Am I supposed to only include the JSPM one because the browser has some data this might need. Also serve files doesn't seem to serve them. So I had to put them in Karma files array and which at least loads files. Babel seems to work.

I keep getting an error saying Require is undefined. Am I supposed to include SystemJs because some libraries use requireJS.

**Comment by rafiwardak2003** [comment]
I have made a fix for this and will be making a pull request that makes this work for the JSPM 0.17 Beta.

**Comment by herclogon** [comment]
I also have made some changes to work with JSPM@beta, take a look https://github.com/herclogon/karma-jspm. It works for me, but I think not production ready.

**Comment by svi3c** [comment]
Works for me: https://github.com/flaviait/ng2-jspm-template/blob/master/karma-dev.conf.js

**Comment by rafiwardak2003** [comment]
It should work now. My PR was merged a few weeks ago.
