### ISSUE TITLE
Still failing on v0.17 beta

### ISSUE THREAD

**Issue by MeoMix** [Workiva/karma-jspm#141]
Hey,

I believe the latest release makes the assumption that `defaultJSExtension: true` is still enabled even for v0.17 projects.

When I specify:

`      loadFiles: ['test/**/*.spec.js'],`

I error out with:

> http://localhost:9876/test/unit/application.spec Failed to load resource: the server responded with a status of 404 (Not Found)

because `.js` has been dropped from the end of the URL.

I am able to work around this with:

```
      paths: {
        'test/*': 'test/*.js'
      }
```

I'm not sure if there is a more elegant solution, but it was surprising to see the `.js` dropped from the request. I believe that is an issue with `karma-jspm`.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Have you tried setting the config option "stripExtension: false" inside your karma config file? (Note that it has to be inside the jspm: {} object in the config.)

**Comment by MeoMix** [comment]
Oh yeah, I see that in the docs now. My bad. I'll double-check that this evening and close the issue once I can confirm.

**Comment by MeoMix** [comment]
Works, yo!
