### ISSUE TITLE
sourcemaps works not correctly with jspm-karma v2.1.0

### ISSUE THREAD

**Issue by SerkanSipahi** [Workiva/karma-jspm#142]
I updated my project from 2.0.3 (works with jspm@0.16.x) to 2.1.0 (works with jspm@0.17.0-beta.11). Everything works fine, all tests passed but the sourcemaps works not correctly. Let me explain shortly the problem. Sometimes I will try to place a breakpoint in a script and it will jump to  several lines down rather than where I'm trying to set it. 

For reproducing do following:
```
git clone https://github.com/SerkanSipahi/app-decorators
cd app-decorators
make install
make test

// then e.g. you can try to set any breakpoint in any spawn browser (test/libs/router.spec.js).

```

My question: is that caused by the jspm-karma or by jspm@0.17.0-beta.11 ( @guybedford )?

**Comment by guybedford** [comment]
This may be related to https://github.com/systemjs/systemjs/pull/1180.

**Comment by SerkanSipahi** [comment]
thanks for fix (@develar) and merging (@guybedford). @guybedford can you deploy a new version in Systemjs and adjust all dependencies packages to them e.g. jspm, ..., etc,

**Comment by SerkanSipahi** [comment]
@guybedford i have updated to jspm 0.17.0-beta.12. Nothing changed. Same issue. What to do? Its reproducible see above.

**Comment by SerkanSipahi** [comment]
To all jspm user -> please update to 0.17.0-beta.22 -> no source maps issues anymore....
