### ISSUE TITLE
jspm 0.17 beta: main entry test files not transpiling JSX

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [Workiva/karma-jspm#143]
Not sure if this is a jspm beta bug, a configuration issue or a karma-jspm issue, was hoping someone could shed some light. https://github.com/jspm/jspm-cli/issues/1671

**Comment by edrex** [comment]
how did you work around this @m-a-r-c-e-l-i-n-o?

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@edrex I gave a [brief explanation](https://github.com/jspm/jspm-cli/issues/1671#issuecomment-204760335) on what was wrong. Basically, I left the configuration as it was and placed my test folder inside the my app folder (i.e. src), and it transpiled along with the my other app files. Do any of your files transpile?

**Comment by edrex** [comment]
Thanks @m-a-r-c-e-l-i-n-o. I eventually got the test files to JSX transform by adding a `meta` key entry for them. Not sure if that should have gone inside the `packages` key instead, but it got me unstuck.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@guybedford ^^ is this a good way to go about adding more files to the JSX transform?

**Comment by guybedford** [comment]
Yes that's a good approach!
