### ISSUE TITLE
Path separator problem.

### ISSUE THREAD

**Issue by ahmedshuhel** [Workiva/karma-jspm#30]
This is a function from `karma-jspm/src/init.js`
```javascrpt
function expandGlob(file) {
  return glob.sync(file.pattern || file).map(function (filePath) {
    return filePath.replace(/\//g, path.sep);
  });
};
```
Is there any specific reason why you are replacing `/` with `\`? This is actually causing `System.import` fail on windows as `path.sep` is `\` in windows. On *nix it is okay I guess because it's essentially doing nothing there.

**Comment by EisenbergEffect** [comment]
@computmaxer It would be great to get this issue fixed as it creates a problem for all Windows users. Any chance I can convince you to merge this above PR soon?

**Comment by maxwellpeterson-wf** [comment]
@EisenbergEffect 1.1.2 has been published with the fix included.

**Comment by EisenbergEffect** [comment]
Awesome!!!

**Comment by ahmedshuhel** [comment]
Thank you
