### ISSUE TITLE
run tests on CI system

### ISSUE THREAD

**Issue by andreasgrimm** [Workiva/karma-jspm#37]
How do you run your tests on a CI system?

PhantomJS isn't working. I'm sick of using SauceLabs to run my unit tests in e.g. Chrome Browser because it increases the build time.

**Comment by maxwellpeterson-wf** [comment]
We use PhantomJS. You may need to include the bind-polyfill for PhantomJS to work well (https://github.com/Workiva/wGulp/blob/master/src/function-bind-polyfill.js)

Ref: https://github.com/ariya/phantomjs/issues/10522

**Comment by andreasgrimm** [comment]
thanks for fast reply. I'll try that out ...

**Comment by andreasgrimm** [comment]
yay, I now can use PhantomJS. Thanks so much!
