### ISSUE TITLE
PhantomJS fails to run with 6to5

### ISSUE THREAD

**Issue by mehcode** [Workiva/karma-jspm#40]
When I run my tests I get an error with PhantomJS although Firefox and Chrome both work.

```
  Error loading "app/main" at /home/ryan/Workspace/launchbadge/paper/app/main.js
  Error loading "@6to5" at /home/ryan/Workspace/launchbadge/paper/jspm_packages/6to5.js
  Error evaluating /home/ryan/Workspace/launchbadge/paper/jspm_packages/6to5.js
  TypeError: 'undefined' is not a function (evaluating 're.test.bind(re)')
  at undefined
```

Repo is at https://github.com/launchbadge/paper

**Comment by adamdicarlo** [comment]
Not sure what the exactly problem/solution is, but PhantomJS (1.x; don't know about 2.x) does not support `Function.prototype.bind` -- so that may be involved.

**Comment by mehcode** [comment]
I'm not sure where to put a shim. However this looks like it'll be fixed with https://github.com/karma-runner/karma-phantomjs-launcher/issues/56

**Comment by adamdicarlo** [comment]
Ah, cool. FWIW, in our case the problem was simply "whoops, Karma's trying to load our gulpfile" (needed to change an exclude list after switching from grunt to gulp)

**Comment by sochka** [comment]
The reason is that Function.prototype.bind is actually es5, not fully supported by phantomjs <2.0

**Comment by deepsweet** [comment]
https://github.com/tschaub/karma-phantomjs-shim
