### ISSUE TITLE
Unable to import JSON files

### ISSUE THREAD

**Issue by lyptt** [Workiva/karma-jspm#57]
In my JSPM project I'm using the JSON plugin '```systemjs/plugin-json```' to allow me to import JSON files into my scripts. 

It seems that this isn't working with karma-jspm. I'm unsure of what I need to do to get these files loading. SystemJS under Karma is acting as if the plugin isn't loaded at all, appending ```.js``` to the end of the filenames.

**Comment by moog16** [comment]
I'm also having this issue. I tried doing things like `systemjs/plugin-json.json`, `systemjs/plugin-json.json!`,  `systemjs/plugin-json.json!json`, and `systemjs/plugin-json.json!text`. None worked :(

**Comment by zyll** [comment]
https://github.com/PacciniBruno/plugin-json/commit/0335cf2d374fc5656d4d0121776656c49f66c19a work for us

**Comment by otroboe** [comment]
Hello !

I tried so may things, but my json file always win a .js extension at the end :(
Do you have any exemple of Karma config and SystemJS config ?

Thank you !
