### ISSUE TITLE
Cannot find es6-module-loader.js

### ISSUE THREAD

**Issue by richburdon** [Workiva/karma-jspm#88]
After setting up JSPM and SystemJS I have a working app, but while configuring Karma and starting the server I get this error.

[watcher] Pattern "MY_PACKAGE_DIR/es6-module-loader.js" does not match any file.

From the karma-jspm docs: https://www.npmjs.com/package/karma-jspm
This plugin assumes you are using jspm in your project. You will need to have a config.js in the root of
your project (though this is configurable) as well as a jspm_packages directory containing systemjs
and the es6-module-loader.

However, the SystemJS docs say:
Built on top of the ES6 Module Loader polyfill.

Is this a problem with karma-jspm or a misconfiguration of jspm itself?
NOTE, my JSPM packages folder does not contain es6-module-loader.js and I cannot find any docs that suggest it should be there (or if it should, how it gets installed).

**Comment by robertbaker** [comment]
@richburdon the es6 module loader is now apart of system.js.

I'm having issues myself with the plugin, but the docs need updated with the latest JSPM@beta changes.

**Comment by maxwellpeterson-wf** [comment]
@richburdon Which versions of jspm and karma-jspm are you using?
If you're using jspm 0.16.0 beta then es6-module-loader.js will no longer be in jspm_packages so you'll need to grab karma-jspm 2.0.1-beta.2.

**Comment by richburdon** [comment]
Thanks. I switched to karma-systemjs which works well (and has working examples in the docs). Are there advantages to karma-jspm that I should consider to try getting that working? Thanks again.

**Comment by robertbaker** [comment]
@maxwellpeterson-wf  jspm 0.18 is out of beta

**Comment by maxwellpeterson-wf** [comment]
@robertbaker [karma-jspm@2.0.1](https://github.com/Workiva/karma-jspm/releases/tag/2.0.1) was released yesterday for use with jspm@0.16.0 stable.
